DROP TABLE IF EXISTS drink_extras;
DROP TABLE IF EXISTS drink_status;
DROP TABLE IF EXISTS drink_status_updates;
DROP TABLE IF EXISTS drink_type;
DROP TABLE IF EXISTS drinks;
DROP TABLE IF EXISTS extras;
DROP TABLE IF EXISTS milk_type;
DROP TABLE IF EXISTS size;